function AllTrk=TerminateVariables(AllTrk,ID)
% used to delete values that are not needed when the tracker number ID is
% terminated
%%
Id2=AllTrk.Trobject(ID).MergeWith;
AllTrk.Trobject(ID).InMerge=0;
if Id2 ~=0
    AllTrk.Trobject(Id2).MergeWith=0;
    AllTrk.Trobject(Id2).InMerge=0;
    AllTrk.Trobject(ID).MergeWith=0;
end
AllTrk.Trobject(ID).A_pos = [];
AllTrk.Trobject(ID).A_neg = [];
AllTrk.Trobject(ID).patcho=[];
AllTrk.Trobject(ID).OnHold=0;
AllTrk.Trobject(ID).ValidTracker=0;% 1

AllTrk.Trobject(ID).dataInfo=[];
AllTrk.Trobject(ID).p=[];% [1886 566 43 100 0]
AllTrk.Trobject(ID).upRate=[];% 5
AllTrk.Trobject(ID).EXEMPLAR_NUM=[];% 2
AllTrk.Trobject(ID).sz=[];% [32 16]
AllTrk.Trobject(ID).psize=[];% [32 16]
AllTrk.Trobject(ID).p0=[];% 2.3256
AllTrk.Trobject(ID).param0=[];% [1886 566 2.6875 0 2.3256 0]
AllTrk.Trobject(ID).param=[];% [1x1 struct]
AllTrk.Trobject(ID).num_p=[];% 100
AllTrk.Trobject(ID).num_n=[];% 200
AllTrk.Trobject(ID).A_pos=[];% [512x120 double]
AllTrk.Trobject(ID).A_neg=[];% [512x440 double]
AllTrk.Trobject(ID).patchsize=[];% [6 6]
AllTrk.Trobject(ID).patchnum=[];% [14 6]
AllTrk.Trobject(ID).Fisize=[];% 50
AllTrk.Trobject(ID).patcho=[];% [36x84 double]
AllTrk.Trobject(ID).Fi=[];% [36x50 double]

AllTrk.Trobject(ID).TwoDPCAparam.F=[];% [1x1 struct]
AllTrk.Trobject(ID).TwoDPCAparam.Group=[];
AllTrk.Trobject(ID).TwoDPCAparam.Train_Data=[];
AllTrk.Trobject(ID).TwoDPCAparam.Aav=[];
AllTrk.Trobject(ID).TwoDPCAparam.TotalNumImages=[];

AllTrk.Trobject(ID).PCAparam.U=[];
AllTrk.Trobject(ID).PCAparam.mu=[];
AllTrk.Trobject(ID).PCAparam.Train_Data=[];
AllTrk.Trobject(ID).PCAparam.Group=[];
AllTrk.Trobject(ID).PCAparam.TotalNumImages=[];
AllTrk.Trobject(ID).PCAparam.U=[];
AllTrk.Trobject(ID).PCAparam.mu=[];


AllTrk.Trobject(ID).paramSR=[];% [1x1 struct]
AllTrk.Trobject(ID).alpha_p=[];% [50x84x998 double]
AllTrk.Trobject(ID).result=[];% [120x6 double]
AllTrk.Trobject(ID).missedDetections=[];% [998x1 double]
AllTrk.Trobject(ID).GetBackCount=[];% 0
AllTrk.Trobject(ID).missedCount=[];% 0
AllTrk.Trobject(ID).RightOrLeft=[];% []
AllTrk.Trobject(ID).KeyFrames=[];% [111 112 113 114 115 116 117 118 119 120]
AllTrk.Trobject(ID).A_posLimitStart=[];% 50
AllTrk.Trobject(ID).A_posLimitEnd=[];% 200
AllTrk.Trobject(ID).A_negLimitStart=[];% 100
AllTrk.Trobject(ID).A_negLimitEnd=[];% 200
AllTrk.Trobject(ID).InOcclusion=[];% 0
AllTrk.Trobject(ID).CountOcclusion=[];% 0
AllTrk.Trobject(ID).StartMergFrame=[];% []
AllTrk.Trobject(ID).EndMergFrame=[];% []
AllTrk.Trobject(ID).OcclusionFrames=[];% []
AllTrk.Trobject(ID).UpdateDone=[];% 0
AllTrk.Trobject(ID).KeyFramesCounter=[];% 35
AllTrk.Trobject(ID).Master=[];% 0
AllTrk.Trobject(ID).OnHoldFrame=[];% 0
AllTrk.Trobject(ID).UpdateSGM=[];% 0
AllTrk.Trobject(ID).InMergeCountSplit=[];% 0
AllTrk.Trobject(ID).StopUpdate=[];% 1
AllTrk.Trobject(ID).SafeZone=[];% 0
AllTrk.Trobject(ID).VInitialx=[];% -1.8000
AllTrk.Trobject(ID).VInitialy=[];% 1.1000
AllTrk.Trobject(ID).InMergewithOcclusion=[];% 0
AllTrk.Trobject(ID).objCenter=[];% [2x1 double]
AllTrk.Trobject(ID).InMergeCount=[];% 0
AllTrk.Trobject(ID).EnterFromLR=[];% 0
AllTrk.Trobject(ID).EnterFromTB=[];% 0
AllTrk.Trobject(ID).X=[];% [4x100 double]
AllTrk.Trobject(ID).Neff=[];% [998x1 double]
AllTrk.Trobject(ID).Wkm1=[];% 0.0050
AllTrk.Trobject(ID).X1=[];% [4x100 double]
AllTrk.Trobject(ID).KeyFramesUSed=[];% [1x25 double]
AllTrk.Trobject(ID).OcclusionDegree=[];% []
AllTrk.Trobject(ID).PartsContribution=[];% []
AllTrk.Trobject(ID).Sigmax=[];% 5
AllTrk.Trobject(ID).SigmaVx=[];% 2
AllTrk.Trobject(ID).Sigmay=[];% 5
AllTrk.Trobject(ID).SigmaVy=[];% 2
AllTrk.Trobject(ID).Last_f=[];% 120
AllTrk.Trobject(ID).MaxLikeLihood=[];% [1x120 double]
AllTrk.Trobject(ID).currentBB=[];% [4x1 double]
AllTrk.Trobject(ID).resultEvaluation=[];% [998x1 double]
AllTrk.Trobject(ID).UseMotionModelAffineORVecolity1=[];% 4
AllTrk.Trobject(ID).UseMotionModelAffineORVecolity2=[];% 4
AllTrk.Trobject(ID).AA_pos=[];% [512x120 double]
AllTrk.Trobject(ID).AA_neg=[];% [512x440 double]
AllTrk.Trobject(ID).alpha_q=[];% [50x84 double]
AllTrk.Trobject(ID).alpha_qq=[];% [50x84 double]
AllTrk.Trobject(ID).paramAll=[];% [1x120 struct]
AllTrk.Trobject(ID).IDSW=[];% [1x85 double]
AllTrk.Trobject(ID).BBresult=[];
AllTrk.Trobject(ID).currentCenter=[];
AllTrk.Trobject(ID).CentersParticles=[];
AllTrk.Trobject(ID).ParticlesWeights=[];
AllTrk.Trobject(ID).SGM.ValidRecon=[];
AllTrk.Trobject(ID).SGM.NonOccludedMask=[];
AllTrk.Trobject(ID).A_poswarp=[];
AllTrk.Trobject(ID).A_negwarp=[];
AllTrk.Trobject(ID).currentBB_NP=[];
AllTrk.Trobject(ID).CenterBB_NP=[];
AllTrk.Trobject(ID).LeftTopWHT=[];

